// export const API_URL = 'http://localhost:3001';
export const API_URL = 'https://aestin-backend.onrender.com';
export const PRODUCT_IMG_PATH = '/assets/images/products/';
export const SHIPPING_CHARGES = 10
export const SHIPPING_TAX = 5
export const CURRENCY_LIST = [
    { id: 'AO', country: 'Angola', value: 'AO', name: 'AOA', symbol: 'Kz' },
    { id: 'AI', country: 'Anguilla', value: 'AI', name: 'XCD', symbol: '$' },
    { id: 'AG', country: 'Antigua & Barbuda', value: 'AG', name: 'XCD', symbol: '$' },
    { id: 'AR', country: 'Argentina', value: 'AR', name: 'ARS', symbol: '$' },
    { id: 'AM', country: 'Armenia', value: 'AM', name: 'AMD', symbol: 'դր.' },
    { id: 'AW', country: 'Aruba', value: 'AW', name: 'AWG', symbol: 'ƒ' },
    { id: 'AU', country: 'Australia', value: 'AU', name: 'AUD', symbol: '$' },
    { id: 'AT', country: 'Austria', value: 'AT', name: 'EUR', symbol: '€' },
    { id: 'AZ', country: 'Azerbaijan', value: 'AZ', name: 'AZN', symbol: '₼' },
    { id: 'BS', country: 'Bahamas', value: 'BS', name: 'BSD', symbol: '$' },
    { id: 'BH', country: 'Bahrain', value: 'BH', name: 'USD', symbol: '$' },
    { id: 'BD', country: 'Bangladesh', value: 'BD', name: 'BDT', symbol: '৳' },
    { id: 'BB', country: 'Barbados', value: 'BB', name: 'BBD', symbol: '$' },
    { id: 'BE', country: 'Belgium', value: 'BE', name: 'EUR', symbol: '€' },
    { id: 'BZ', country: 'Belize', value: 'BZ', name: 'BZD', symbol: '$' },
    { id: 'BJ', country: 'Benin', value: 'BJ', name: 'XOF', symbol: 'Fr' },
    { id: 'BM', country: 'Bermuda', value: 'BM', name: 'USD', symbol: '$' },
    { id: 'BT', country: 'Bhutan', value: 'BT', name: 'USD', symbol: '$' },
    { id: 'BO', country: 'Bolivia', value: 'BO', name: 'BOB', symbol: 'Bs.' },
    { id: 'BA', country: 'Bosnia & Herzegovina', value: 'BA', name: 'BAM', symbol: 'КМ' },
    { id: 'BW', country: 'Botswana', value: 'BW', name: 'BWP', symbol: 'P' },
    { id: 'BR', country: 'Brazil', value: 'BR', name: 'BRL', symbol: 'R$' },
    { id: 'VG', country: 'British Virgin Islands', value: 'VG', name: 'USD', symbol: '$' },
    { id: 'BN', country: 'Brunei', value: 'BN', name: 'BND', symbol: '$' },
    { id: 'BG', country: 'Bulgaria', value: 'BG', name: 'BGN', symbol: 'лв.' },
    { id: 'BF', country: 'Burkina Faso', value: 'BF', name: 'XOF', symbol: 'Fr' },
    { id: 'BI', country: 'Burundi', value: 'BI', name: 'BIF', symbol: 'Fr' },
    { id: 'KH', country: 'Cambodia', value: 'KH', name: 'KHR', symbol: '៛' },
    { id: 'CM', country: 'Cameroon', value: 'CM', name: 'XAF', symbol: 'Fr' },
    { id: 'CA', country: 'Canada', value: 'CA', name: 'CAD', symbol: '$' },
    { id: 'CV', country: 'Cape Verde', value: 'CV', name: 'CVE', symbol: '$' },
    { id: 'KY', country: 'Cayman Islands', value: 'KY', name: 'KYD', symbol: '$' },
    { id: 'TD', country: 'Chad', value: 'TD', name: 'XAF', symbol: 'Fr' },
    { id: 'CL', country: 'Chile', value: 'CL', name: 'CLP', symbol: '$' },
    { id: 'CN', country: 'China', value: 'CN', name: 'CNY', symbol: '¥' },
    { id: 'CO', country: 'Colombia', value: 'CO', name: 'COP', symbol: '$' },
    { id: 'KM', country: 'Comoros', value: 'KM', name: 'KMF', symbol: 'Fr' },
    { id: 'CD', country: 'Congo - Kinshasa', value: 'CD', name: 'CDF', symbol: 'Fr' },
    { id: 'CK', country: 'Cook Islands', value: 'CK', name: 'NZD', symbol: '$' },
    { id: 'CR', country: 'Costa Rica', value: 'CR', name: 'CRC', symbol: '₡' },
    { id: 'CI', country: 'Côte d’Ivoire', value: 'CI', name: 'XOF', symbol: 'Fr' },
    { id: 'HR', country: 'Croatia', value: 'HR', name: 'EUR', symbol: '€' },
    { id: 'CW', country: 'Curaçao', value: 'CW', name: 'ANG', symbol: 'ƒ' },
    { id: 'CY', country: 'Cyprus', value: 'CY', name: 'EUR', symbol: '€' },
    { id: 'CZ', country: 'Czechia', value: 'CZ', name: 'CZK', symbol: 'Kč' },
    { id: 'DK', country: 'Denmark', value: 'DK', name: 'DKK', symbol: 'kr.' },
    { id: 'DJ', country: 'Djibouti', value: 'DJ', name: 'DJF', symbol: 'Fdj' },
    { id: 'DM', country: 'Dominica', value: 'DM', name: 'XCD', symbol: '$' },
    { id: 'DO', country: 'Dominican Republic', value: 'DO', name: 'DOP', symbol: '$' },
    { id: 'EC', country: 'Ecuador', value: 'EC', name: 'USD', symbol: '$' },
    { id: 'EG', country: 'Egypt', value: 'EG', name: 'EGP', symbol: 'ج.م' },
    { id: 'SV', country: 'El Salvador', value: 'SV', name: 'USD', symbol: '$' },
    { id: 'GQ', country: 'Equatorial Guinea', value: 'GQ', name: 'XAF', symbol: 'Fr' },
    { id: 'EE', country: 'Estonia', value: 'EE', name: 'EUR', symbol: '€' },
    { id: 'SZ', country: 'Eswatini', value: 'SZ', name: 'SZL', symbol: 'E' },
    { id: 'ET', country: 'Ethiopia', value: 'ET', name: 'ETB', symbol: 'Br' },
    { id: 'FK', country: 'Falkland Islands', value: 'FK', name: 'FKP', symbol: '£' },
    { id: 'FO', country: 'Faroe Islands', value: 'FO', name: 'DKK', symbol: 'kr.' },
    { id: 'FJ', country: 'Fiji', value: 'FJ', name: 'FJD', symbol: '$' },
    { id: 'FI', country: 'Finland', value: 'FI', name: 'EUR', symbol: '€' },
    { id: 'FR', country: 'France', value: 'FR', name: 'EUR', symbol: '€' },
    { id: 'GF', country: 'French Guiana', value: 'GF', name: 'EUR', symbol: '€' },
    { id: 'PF', country: 'French Polynesia', value: 'PF', name: 'XPF', symbol: 'Fr' },
    { id: 'GA', country: 'Gabon', value: 'GA', name: 'USD', symbol: '$' },
    { id: 'GE', country: 'Georgia', value: 'GE', name: 'GEL', symbol: 'ლ' },
    { id: 'DE', country: 'Germany', value: 'DE', name: 'EUR', symbol: '€' },
    { id: 'GH', country: 'Ghana', value: 'GH', name: 'USD', symbol: '$' },
    { id: 'GI', country: 'Gibraltar', value: 'GI', name: 'GBP', symbol: '£' },
    { id: 'GR', country: 'Greece', value: 'GR', name: 'EUR', symbol: '€' },
    { id: 'GL', country: 'Greenland', value: 'GL', name: 'DKK', symbol: 'kr.' },
    { id: 'GD', country: 'Grenada', value: 'GD', name: 'XCD', symbol: '$' },
    { id: 'GP', country: 'Guadeloupe', value: 'GP', name: 'EUR', symbol: '€' },
    { id: 'GT', country: 'Guatemala', value: 'GT', name: 'GTQ', symbol: 'Q' },
    { id: 'GG', country: 'Guernsey', value: 'GG', name: 'GBP', symbol: '£' },
    { id: 'GN', country: 'Guinea', value: 'GN', name: 'GNF', symbol: 'Fr' },
    { id: 'GW', country: 'Guinea-Bissau', value: 'GW', name: 'XOF', symbol: 'Fr' },
    { id: 'GY', country: 'Guyana', value: 'GY', name: 'GYD', symbol: '$' },
    { id: 'HT', country: 'Haiti', value: 'HT', name: 'HTG', symbol: 'G' },
    { id: 'HN', country: 'Honduras', value: 'HN', name: 'HNL', symbol: 'L' },
    { id: 'HK', country: 'Hong Kong SAR', value: 'HK', name: 'HKD', symbol: '$' },
    { id: 'HU', country: 'Hungary', value: 'HU', name: 'HUF', symbol: 'Ft' },
    { id: 'IS', country: 'Iceland', value: 'IS', name: 'ISK', symbol: 'kr' },
    { id: 'IN', country: 'India', value: 'IN', name: 'INR', symbol: '₹' },
    { id: 'ID', country: 'Indonesia', value: 'ID', name: 'IDR', symbol: 'Rp' },
    { id: 'IE', country: 'Ireland', value: 'IE', name: 'EUR', symbol: '€' },
    { id: 'IM', country: 'Isle of Man', value: 'IM', name: 'GBP', symbol: '£' },
    { id: 'IL', country: 'Israel', value: 'IL', name: 'ILS', symbol: '₪' },
    { id: 'IT', country: 'Italy', value: 'IT', name: 'EUR', symbol: '€' },
    { id: 'JM', country: 'Jamaica', value: 'JM', name: 'JMD', symbol: '$' },
    { id: 'JP', country: 'Japan', value: 'JP', name: 'JPY', symbol: '¥' },
    { id: 'JE', country: 'Jersey', value: 'JE', name: 'GBP', symbol: '£' },
    { id: 'JO', country: 'Jordan', value: 'JO', name: 'USD', symbol: '$' },
    { id: 'KZ', country: 'Kazakhstan', value: 'KZ', name: 'KZT', symbol: '〒' },
    { id: 'KE', country: 'Kenya', value: 'KE', name: 'KES', symbol: 'KSh' },
    { id: 'KI', country: 'Kiribati', value: 'KI', name: 'USD', symbol: '$' },
    { id: 'KW', country: 'Kuwait', value: 'KW', name: 'USD', symbol: '$' },
    { id: 'KG', country: 'Kyrgyzstan', value: 'KG', name: 'KGS', symbol: 'som' },
    { id: 'LA', country: 'Laos', value: 'LA', name: 'LAK', symbol: '₭' },
    { id: 'LV', country: 'Latvia', value: 'LV', name: 'EUR', symbol: '€' },
    { id: 'LB', country: 'Lebanon', value: 'LB', name: 'LBP', symbol: 'ل.ل' },
    { id: 'LS', country: 'Lesotho', value: 'LS', name: 'LSL', symbol: 'L' },
    { id: 'LR', country: 'Liberia', value: 'LR', name: 'LRD', symbol: '$' },
    { id: 'LI', country: 'Liechtenstein', value: 'LI', name: 'CHF', symbol: 'CHF' },
    { id: 'LT', country: 'Lithuania', value: 'LT', name: 'EUR', symbol: '€' },
    { id: 'LU', country: 'Luxembourg', value: 'LU', name: 'EUR', symbol: '€' },
    { id: 'MO', country: 'Macao SAR', value: 'MO', name: 'MOP', symbol: 'P' },
    { id: 'MG', country: 'Madagascar', value: 'MG', name: 'USD', symbol: '$' },
    { id: 'MW', country: 'Malawi', value: 'MW', name: 'MWK', symbol: 'MK' },
    { id: 'MY', country: 'Malaysia', value: 'MY', name: 'MYR', symbol: 'RM' },
    { id: 'MV', country: 'Maldives', value: 'MV', name: 'MVR', symbol: 'MVR' },
    { id: 'MT', country: 'Malta', value: 'MT', name: 'EUR', symbol: '€' },
    { id: 'MQ', country: 'Martinique', value: 'MQ', name: 'EUR', symbol: '€' },
    { id: 'MR', country: 'Mauritania', value: 'MR', name: 'USD', symbol: '$' },
    { id: 'MU', country: 'Mauritius', value: 'MU', name: 'MUR', symbol: '₨' },
    { id: 'YT', country: 'Mayotte', value: 'YT', name: 'EUR', symbol: '€' },
    { id: 'MX', country: 'Mexico', value: 'MX', name: 'MXN', symbol: '$' },
    { id: 'MD', country: 'Moldova', value: 'MD', name: 'MDL', symbol: 'L' },
    { id: 'MC', country: 'Monaco', value: 'MC', name: 'EUR', symbol: '€' },
    { id: 'MN', country: 'Mongolia', value: 'MN', name: 'MNT', symbol: '₮' },
    { id: 'ME', country: 'Montenegro', value: 'ME', name: 'EUR', symbol: '€' },
    { id: 'MS', country: 'Montserrat', value: 'MS', name: 'XCD', symbol: '$' },
    { id: 'MA', country: 'Morocco', value: 'MA', name: 'MAD', symbol: 'د.م.' },
    { id: 'MZ', country: 'Mozambique', value: 'MZ', name: 'MZN', symbol: 'MTn' },
    { id: 'NA', country: 'Namibia', value: 'NA', name: 'NAD', symbol: '$' },
    { id: 'NR', country: 'Nauru', value: 'NR', name: 'AUD', symbol: '$' },
    { id: 'NP', country: 'Nepal', value: 'NP', name: 'NPR', symbol: '₨' },
    { id: 'NL', country: 'Netherlands', value: 'NL', name: 'EUR', symbol: '€' },
    { id: 'NC', country: 'New Caledonia', value: 'NC', name: 'XPF', symbol: 'Fr' },
    { id: 'NZ', country: 'New Zealand', value: 'NZ', name: 'NZD', symbol: '$' },
    { id: 'NI', country: 'Nicaragua', value: 'NI', name: 'NIO', symbol: 'C$' },
    { id: 'NG', country: 'Nigeria', value: 'NG', name: 'NGN', symbol: '₦' },
    { id: 'NU', country: 'Niue', value: 'NU', name: 'NZD', symbol: '$' },
    { id: 'MK', country: 'North Macedonia', value: 'MK', name: 'MKD', symbol: 'ден' },
    { id: 'NO', country: 'Norway', value: 'NO', name: 'NOK', symbol: 'kr' },
    { id: 'OM', country: 'Oman', value: 'OM', name: 'USD', symbol: '$' },
    { id: 'PK', country: 'Pakistan', value: 'PK', name: 'PKR', symbol: '₨' },
    { id: 'PA', country: 'Panama', value: 'PA', name: 'USD', symbol: '$' },
    { id: 'PG', country: 'Papua New Guinea', value: 'PG', name: 'PGK', symbol: 'K' },
    { id: 'PY', country: 'Paraguay', value: 'PY', name: 'PYG', symbol: '₲' },
    { id: 'PE', country: 'Peru', value: 'PE', name: 'PEN', symbol: 'S/.' },
    { id: 'PH', country: 'Philippines', value: 'PH', name: 'PHP', symbol: '₱' },
    { id: 'PL', country: 'Poland', value: 'PL', name: 'PLN', symbol: 'zł' },
    { id: 'PT', country: 'Portugal', value: 'PT', name: 'EUR', symbol: '€' },
    { id: 'QA', country: 'Qatar', value: 'QA', name: 'QAR', symbol: 'ر.ق' },
    { id: 'RE', country: 'Réunion', value: 'RE', name: 'EUR', symbol: '€' },
    { id: 'RO', country: 'Romania', value: 'RO', name: 'RON', symbol: 'Lei' },
    { id: 'RW', country: 'Rwanda', value: 'RW', name: 'RWF', symbol: 'FRw' },
    { id: 'WS', country: 'Samoa', value: 'WS', name: 'WST', symbol: 'T' },
    { id: 'SM', country: 'San Marino', value: 'SM', name: 'EUR', symbol: '€' },
    { id: 'ST', country: 'São Tomé & Príncipe', value: 'ST', name: 'STD', symbol: 'Db' },
    { id: 'SA', country: 'Saudi Arabia', value: 'SA', name: 'SAR', symbol: 'ر.س' },
    { id: 'RS', country: 'Serbia', value: 'RS', name: 'RSD', symbol: 'РСД' },
    { id: 'SC', country: 'Seychelles', value: 'SC', name: 'SCR', symbol: '₨' },
    { id: 'SL', country: 'Sierra Leone', value: 'SL', name: 'SLL', symbol: 'Le' },
    { id: 'SG', country: 'Singapore', value: 'SG', name: 'SGD', symbol: '$' },
    { id: 'SX', country: 'Sint Maarten', value: 'SX', name: 'ANG', symbol: 'ƒ' },
    { id: 'SK', country: 'Slovakia', value: 'SK', name: 'EUR', symbol: '€' },
    { id: 'SI', country: 'Slovenia', value: 'SI', name: 'EUR', symbol: '€' },
    { id: 'SB', country: 'Solomon Islands', value: 'SB', name: 'SBD', symbol: '$' },
    { id: 'ZA', country: 'South Africa', value: 'ZA', name: 'ZAR', symbol: 'R' },
    { id: 'KR', country: 'South Korea', value: 'KR', name: 'KRW', symbol: '₩' },
    { id: 'ES', country: 'Spain', value: 'ES', name: 'EUR', symbol: '€' },
    { id: 'LK', country: 'Sri Lanka', value: 'LK', name: 'LKR', symbol: '₨' },
    { id: 'BL', country: 'St. Barthélemy', value: 'BL', name: 'EUR', symbol: '€' },
    { id: 'SH', country: 'St. Helena', value: 'SH', name: 'SHP', symbol: '£' },
    { id: 'KN', country: 'St. Kitts & Nevis', value: 'KN', name: 'XCD', symbol: '$' },
    { id: 'LC', country: 'St. Lucia', value: 'LC', name: 'XCD', symbol: '$' },
    { id: 'MF', country: 'St. Martin', value: 'MF', name: 'EUR', symbol: '€' },
    { id: 'VC', country: 'St. Vincent & Grenadines', value: 'VC', name: 'XCD', symbol: '$' },
    { id: 'SR', country: 'Suriname', value: 'SR', name: 'SRD', symbol: '$' },
    { id: 'SE', country: 'Sweden', value: 'SE', name: 'SEK', symbol: 'kr' },
    { id: 'CH', country: 'Switzerland', value: 'CH', name: 'CHF', symbol: 'CHF' },
    { id: 'TW', country: 'Taiwan', value: 'TW', name: 'TWD', symbol: '$' },
    { id: 'TZ', country: 'Tanzania', value: 'TZ', name: 'TZS', symbol: 'Sh' },
    { id: 'TH', country: 'Thailand', value: 'TH', name: 'THB', symbol: '฿' },
    { id: 'TL', country: 'Timor-Leste', value: 'TL', name: 'USD', symbol: '$' },
    { id: 'TG', country: 'Togo', value: 'TG', name: 'XOF', symbol: 'Fr' },
    { id: 'TO', country: 'Tonga', value: 'TO', name: 'TOP', symbol: '$' },
    { id: 'TT', country: 'Trinidad & Tobago', value: 'TT', name: 'TTD', symbol: '$' },
    { id: 'TN', country: 'Tunisia', value: 'TN', name: 'USD', symbol: '$' },
    { id: 'TR', country: 'Türkiye', value: 'TR', name: 'TRY', symbol: '₺' },
    { id: 'TM', country: 'Turkmenistan', value: 'TM', name: 'USD', symbol: '$' },
    { id: 'TC', country: 'Turks & Caicos Islands', value: 'TC', name: 'USD', symbol: '$' },
    { id: 'TV', country: 'Tuvalu', value: 'TV', name: 'AUD', symbol: '$' },
    { id: 'UG', country: 'Uganda', value: 'UG', name: 'UGX', symbol: 'USh' },
    { id: 'AE', country: 'United Arab Emirates', value: 'AE', name: 'AED', symbol: 'د.إ' },
    { id: 'GB', country: 'United Kingdom', value: 'GB', name: 'GBP', symbol: '£' },
    { id: 'US', country: 'United States', value: 'US', name: 'USD', symbol: '$' },
    { id: 'UY', country: 'Uruguay', value: 'UY', name: 'UYU', symbol: '$' },
    { id: 'UZ', country: 'Uzbekistan', value: 'UZ', name: 'UZS', symbol: 'UZS' },
    { id: 'VU', country: 'Vanuatu', value: 'VU', name: 'VUV', symbol: 'Vt' },
    { id: 'VA', country: 'Vatican City', value: 'VA', name: 'EUR', symbol: '€' },
    { id: 'VE', country: 'Venezuela', value: 'VE', name: 'USD', symbol: '$' },
    { id: 'VN', country: 'Vietnam', value: 'VN', name: 'VND', symbol: '₫' },
    { id: 'WF', country: 'Wallis & Futuna', value: 'WF', name: 'XPF', symbol: 'Fr' },
    { id: 'ZM', country: 'Zambia', value: 'ZM', name: 'ZMW', symbol: 'ZK' },
    { id: 'ZW', country: 'Zimbabwe', value: 'ZW', name: 'USD', symbol: '$' },
]